name: reviewdog
on: [pull_request]

jobs:
  tflint:
    name: runner / tflint
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: tflint
          uses: reviewdog/action-tflint@master
          with:
            github_token: ${{ secrets.GH_TOKEN }}
            working_directory: "terraform" # Optional. Change working directory
            fail_on_error: "true" # Optional. Fail action if errors are found
            filter_mode: "nofilter" # Optional. Check all files, not just the diff
