name: "TFlint - staging"
on:
  pull_request:
    paths:
    - "terraform/stg/**"
jobs:
  tflint:
    name: runner
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.26

      - name: Terraform init
        run: |
          cd terraform/stg
          terraform init
          
      - name: tflint stg
        uses: reviewdog/action-tflint@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          working_directory: "terraform/stg" # Optional. Change working directory
          reporter: github-pr-check
          fail_on_error: "true" # Optional. Fail action if errors are found
          filter_mode: "nofilter" # Optional. Check all files, not just the diff
          flags: "--module" # Optional. Add custom tflint flags
