name: 'Terraform checks'
on:
  pull_request:
    paths:
    - "terraform/**"

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.26
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: 'terraform'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: 'TF Lint'
        uses: actions/@notrenderfarm/tflint-action@v1
        with:
          directory: 'terraform'
